#!/bin/bash
set -e

echo "=== getMe Installer ==="

# 1. OS and Architecture Check
OS="$(uname -s)"
ARCH="$(uname -m)"

if [[ "$OS" == "MINGW"* || "$OS" == "CYGWIN"* || "$OS" == "MSYS"* ]]; then
    echo "Error: Windows is not natively supported by this install script."
    echo "Please use WSL (Windows Subsystem for Linux) or Docker."
    exit 1
elif [[ "$OS" != "Linux" && "$OS" != "Darwin" ]]; then
    echo "Error: Unsupported operating system: $OS"
    exit 1
fi

if [ "$ARCH" = "x86_64" ]; then
    ARCH="amd64"
elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    ARCH="arm64"
else
    echo "Error: Unsupported architecture: $ARCH"
    exit 1
fi

OS_LOWER=$(echo "$OS" | tr '[:upper:]' '[:lower:]')
echo "Detected Environment: $OS_LOWER $ARCH"

# 2. Fetch Latest Release Version (Assumes GitHub Releases exist)
GITHUB_REPO="AatirNadim/getMe" # Replace with actual org if different

echo "Fetching latest release information..."
# Fetch up to 100 recent releases to ensure we find the latest for both prefixes
RELEASES_JSON=$(curl -s "https://api.github.com/repos/${GITHUB_REPO}/releases?per_page=100")

# Extract the most recently published tags matching our specific component prefixes
LATEST_SERVER_TAG=$(echo "$RELEASES_JSON" | grep '"tag_name":' | grep '"getme-server/v' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')
LATEST_CLI_TAG=$(echo "$RELEASES_JSON" | grep '"tag_name":' | grep '"getme-cli/v' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')

if [ -z "$LATEST_SERVER_TAG" ] || [ -z "$LATEST_CLI_TAG" ]; then
    echo "[WARN] Could not automatically determine latest tags from GitHub API."
    echo "This may be because no releases have been published yet, or API rate limits were hit."
    echo "Please compile from source or check GitHub Actions."
    exit 1
fi

echo "Found Server Version: $LATEST_SERVER_TAG"
echo "Found CLI Version: $LATEST_CLI_TAG"

# 3. Download the Tarballs
# The tarballs generated by our CI follow this strict naming convention
SERVER_TAR="getMe-server-${OS_LOWER}-${ARCH}.tar.gz"
CLI_TAR="getme-${OS_LOWER}-${ARCH}.tar.gz"

SERVER_URL="https://github.com/${GITHUB_REPO}/releases/download/${LATEST_SERVER_TAG}/${SERVER_TAR}"
CLI_URL="https://github.com/${GITHUB_REPO}/releases/download/${LATEST_CLI_TAG}/${CLI_TAR}"

echo "Downloading Server ($SERVER_TAR)..."
curl -sL "$SERVER_URL" -o "/tmp/$SERVER_TAR"

echo "Downloading CLI ($CLI_TAR)..."
curl -sL "$CLI_URL" -o "/tmp/$CLI_TAR"

# 4. Extract and Install
echo "Installing binaries..."
sudo mkdir -p /opt/getme
sudo mkdir -p /usr/local/bin

# The tarballs contain exactly the executable file (no wrapper folder)
sudo tar -xzf "/tmp/$SERVER_TAR" -C /opt/getme/
sudo tar -xzf "/tmp/$CLI_TAR" -C /usr/local/bin/t exist. Please run the setup sc

# Ensure they are executable
sudo chmod +x /opt/getme/getMe-server
sudo chmod +x /usr/local/bin/getme

# Clean up temp files
rm -f "/tmp/$SERVER_TAR" "/tmp/$CLI_TAR"

# 5. Setup Directories and Permissions
echo "Setting up Data and Log directories..."
OWNER_USER=${SUDO_USER:-$(whoami)}

BASE_DIR="/var/lib/getMeStore/dataDir"
STORE_DIR="$BASE_DIR/segments"
COMPACTED_DIR="$BASE_DIR/compactedSegments"
SOCK_DIR="/tmp/getMeStore/sockDir"
LOG_DIR="/tmp/getMeStore/dumpDir"

sudo mkdir -p "$STORE_DIR" "$COMPACTED_DIR" "$SOCK_DIR" "$LOG_DIR"

# Assign ownership of the data directories to the executing (non-root) user
sudo chown -R "$OWNER_USER:$OWNER_USER" "$BASE_DIR"

# Note: /tmp directories will naturally be owned by the user if the server spawns them, 
# but setting them up safely here explicitly avoids permission conflicts.
sudo mkdir -p /tmp/getMeStore
sudo chown -R "$OWNER_USER:$OWNER_USER" /tmp/getMeStore
sudo chmod 700 "$SOCK_DIR" "$LOG_DIR"

echo "=== getMe Installation Complete ==="
echo "You can now run 'getme start-server' to launch the database."
