#!/bin/bash
set -e

# Global Configurations
GITHUB_REPO="AatirNadim/getMe"
OS_LOWER=""
ARCH=""
LATEST_SERVER_TAG=""
LATEST_CLI_TAG=""
SERVER_TAR=""
CLI_TAR=""
OWNER_USER="${SUDO_USER:-$(whoami)}"

print_header() {
    echo "=== getMe Installer ==="
}

detect_environment() {
    echo "Detecting operating system and architecture..."
    local os_name
    os_name="$(uname -s)"
    local arch_name
    arch_name="$(uname -m)"

    if [[ "$os_name" == "MINGW"* || "$os_name" == "CYGWIN"* || "$os_name" == "MSYS"* ]]; then
        echo "Error: Windows is not natively supported by this install script."
        echo "Please use WSL (Windows Subsystem for Linux) or Docker."
        exit 1
    elif [[ "$os_name" != "Linux" && "$os_name" != "Darwin" ]]; then
        echo "Error: Unsupported operating system: $os_name"
        exit 1
    fi

    if [ "$arch_name" = "x86_64" ]; then
        ARCH="amd64"
    elif [ "$arch_name" = "aarch64" ] || [ "$arch_name" = "arm64" ]; then
        ARCH="arm64"
    else
        echo "Error: Unsupported architecture: $arch_name"
        exit 1
    fi

    OS_LOWER=$(echo "$os_name" | tr '[:upper:]' '[:lower:]')
    echo "Detected Environment: $OS_LOWER $ARCH"
}

fetch_latest_tags() {
    echo "Fetching latest release information..."
    # Fetch up to 100 recent releases to ensure we find the latest for both prefixes
    local releases_json
    releases_json=$(curl -s "https://api.github.com/repos/${GITHUB_REPO}/releases?per_page=100")

    # Extract the most recently published tags matching our specific component prefixes
    LATEST_SERVER_TAG=$(echo "$releases_json" | grep '"tag_name":' | grep '"getme-server/v' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')
    LATEST_CLI_TAG=$(echo "$releases_json" | grep '"tag_name":' | grep '"getme-cli/v' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')

    if [ -z "$LATEST_SERVER_TAG" ] || [ -z "$LATEST_CLI_TAG" ]; then
        echo "[WARN] Could not automatically determine latest tags from GitHub API."
        echo "This may be because no releases have been published yet, or API rate limits were hit."
        echo "Please compile from source or check GitHub Actions."
        exit 1
    fi

    echo "Found Server Version: $LATEST_SERVER_TAG"
    echo "Found CLI Version: $LATEST_CLI_TAG"
}

download_binaries() {
    # The tarballs generated by our CI follow this strict naming convention
    SERVER_TAR="getMe-server-${OS_LOWER}-${ARCH}.tar.gz"
    CLI_TAR="getme-cli-${OS_LOWER}-${ARCH}.tar.gz"

    # GitHub natively supports unencoded slashes for the releases/download endpoint
    # (e.g. releases/download/getme-server/v0.0.1/getMe-server...)
    local server_url="https://github.com/${GITHUB_REPO}/releases/download/${LATEST_SERVER_TAG}/${SERVER_TAR}"
    local cli_url="https://github.com/${GITHUB_REPO}/releases/download/${LATEST_CLI_TAG}/${CLI_TAR}"

    echo "Downloading Server ($SERVER_TAR)..."
    curl -fL "$server_url" -o "/tmp/$SERVER_TAR" || { echo "Error: Failed to download Server binary"; exit 1; }

    echo "Downloading CLI ($CLI_TAR)..."
    curl -fL "$cli_url" -o "/tmp/$CLI_TAR" || { echo "Error: Failed to download CLI binary"; exit 1; }
}

install_binaries() {
    echo "Installing binaries..."
    sudo mkdir -p /opt/getme
    sudo mkdir -p /usr/local/bin

    # The tarballs contain exactly the executable file (no wrapper folder)
    sudo tar -xzf "/tmp/$SERVER_TAR" -C /opt/getme/
    sudo tar -xzf "/tmp/$CLI_TAR" -C /usr/local/bin/

    # Ensure they are executable
    sudo chmod +x /opt/getme/getMe-server
    sudo chmod +x /usr/local/bin/getme-cli

    # Create a convenience symlink so the command can be run as 'getme'
    sudo ln -sf /usr/local/bin/getme-cli /usr/local/bin/getme

    # Clean up temp files
    rm -f "/tmp/$SERVER_TAR" "/tmp/$CLI_TAR"
}

setup_directories() {
    echo "Setting up Data and Log directories..."
    
    local base_dir="/var/lib/getMeStore/dataDir"
    local store_dir="$base_dir/segments"
    local compacted_dir="$base_dir/compactedSegments"
    local sock_dir="/tmp/getMeStore/sockDir"
    local log_dir="/tmp/getMeStore/dumpDir"

    sudo mkdir -p "$store_dir" "$compacted_dir" "$sock_dir" "$log_dir"

    local owner_group
    owner_group=$(id -gn "$OWNER_USER")

    # Assign ownership of the data directories to the executing (non-root) user
    sudo chown -R "$OWNER_USER:$owner_group" "$base_dir"

    # Note: /tmp directories will naturally be owned by the user if the server spawns them, 
    # but setting them up safely here explicitly avoids permission conflicts.
    sudo mkdir -p /tmp/getMeStore
    sudo chown -R "$OWNER_USER:$owner_group" /tmp/getMeStore
    sudo chmod 700 "$sock_dir" "$log_dir"
}

check_path() {
    if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
        echo ""
        echo "======================================================================"
        echo " WARNING: /usr/local/bin is not in your PATH."
        echo " The 'getme' command will not work globally until you add it."
        echo " Please add it to your current session by running:"
        echo "   export PATH=\"\$PATH:/usr/local/bin\""
        echo " Consider adding this line to your ~/.bashrc, ~/.zshrc, or ~/.profile."
        echo "======================================================================"
        echo ""
    fi
}

main() {
    print_header
    detect_environment
    fetch_latest_tags
    download_binaries
    install_binaries
    setup_directories
    check_path
    
    echo "=== getMe Installation Complete ==="
    echo "You can now run 'getme start-server' to launch the database."
}

# Execute main function
main
