# Stage 1: Build the Go application
FROM golang:1.23.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/dist/getMe .

FROM alpine:latest AS final

ARG UID=1000
ARG GID=1000

# --- Running as root ---
RUN mkdir -p /var/lib/getMeStore/dataDir

RUN addgroup -g ${GID} appgroup && \
    adduser -u ${UID} -G appgroup -D appuser

# --- Making the added user the owner of the data directory ---
RUN chown -R appuser:appgroup /var/lib/getMeStore

USER appuser

# --- Now running as appuser ---
RUN mkdir -p /tmp/getMeStore/dumpDir && \
    mkdir -p /tmp/getMeStore/sockDir

COPY --from=builder /app/dist/getMe /getMe

CMD [ "/getMe" ]