name: Lint Go Modules

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [cli, commons, http-proxy-go, sdks/goSdk, server, server/tests, utils]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2
          working-directory: ${{ matrix.module }}
