name: Publish Java SDK to Maven Central

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major, minor, patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  check-main-branch:
    uses: ./.github/workflows/reusable-enforce-main-branch.yml

  tag-and-release:
    needs: check-main-branch
    uses: ./.github/workflows/reusable-sdk-release.yml
    with:
      release_type: ${{ github.event.inputs.release_type }}
      sdk_path: "sdks/javaSdk"

  publish-maven-central:
    needs: tag-and-release
    name: Build and Publish Java SDK
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./sdks/javaSdk

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.tag-and-release.outputs.new_tag }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Publish to Central Portal
        run: ./gradlew publishAndReleaseToMavenCentral --no-daemon
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
